export const countryData = [
    { timezone: "Africa/Algiers",country: "Algeria",city: "Oran",region:"Europe"},
    { timezone: "Europe/Andorra",country: "Andorra",city: "Andorra La Vella",region:"Europe"},
    { timezone: "Africa/Luanda",country: "Angola",city: "Luanda",region:"MEA"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "BahIa Blanca",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Corrientes",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Jujuy",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Mar del Plata",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Mendoza",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Moron",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Parana",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Posadas",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Resistencia",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Rosario",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Salta",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "San Juan",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "San Miguel de Tucuman",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "Santa Fe",region:"America"},
    { timezone: "America/Argentina/Mendoza",country: "Argentina",city: "SDE",region:"America"},
    { timezone: "Asia/Yerevan",country: "Armenia",city: "Gyumri",region:"Europe"},
    { timezone: "Asia/Yerevan",country: "Armenia",city: "Vanadzor",region:"Europe"},
    { timezone: "Asia/Yerevan",country: "Armenia",city: "Yerevan",region:"Europe"},
    { timezone: "Australia/Perth",country: "Australia",city: "Perth",region:"Oceania"},
    { timezone: "Australia/Adelaide",country: "Australia",city: "Adelaide",region:"Oceania"},
    { timezone: "Australia/Darwin",country: "Australia",city: "Darwin",region:"Oceania"},
    { timezone: "Australia/Brisbane",country: "Australia",city: "Brisbane",region:"Oceania"},
    { timezone: "Australia/Sydney",country: "Australia",city: "Canberra",region:"Oceania"},
    { timezone: "Australia/Melbourne",country: "Australia",city: "Cranbourne",region:"Oceania"},
    { timezone: "Australia/Brisbane",country: "Australia",city: "Gold Coast",region:"Oceania"},
    { timezone: "Australia/Hobart",country: "Australia",city: "Hobart",region:"Oceania"},
    { timezone: "Australia/Melbourne",country: "Australia",city: "Melbourne",region:"Oceania"},
    { timezone: "Australia/Sydney",country: "Australia",city: "Newcastle",region:"Oceania"},
    { timezone: "Australia/Sydney",country: "Australia",city: "Sydney",region:"Oceania"},
    { timezone: "Australia/Sydney" ,country: "Australia",city: "Wollongong",region:"Oceania"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Graz",region:"Europe"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Innsbruck",region:"Europe"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Klagenfurt",region:"Europe"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Linz",region:"Europe"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Salzburg",region:"Europe"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Vienna",region:"Europe"},
    { timezone: "Europe/Vienna",country: "Austria",city: "Wiener Neustadt",region:"Europe"},
    { timezone: "Asia/Baku",country: "Azerbaijan",city: "Lankaran",region:"Europe"},
    { timezone: "Asia/Baku",country: "Azerbaijan",city: "Stepanakert",region:"Europe"},
    { timezone: "Asia/Baku" ,country: "Azerbaijan",city: "Yevlax",region:"Europe"},
    { timezone: "Asia/Bahrain",country: "Bahrain",city: "Manama",region:"MEA"},
    { timezone: "Asia/Dhaka",country: "Bangladesh",city: "Chittagong",region:"APAC"},
    { timezone: "Asia/Dhaka",country: "Bangladesh",city: "Dhaka",region:"APAC"},
    { timezone: "Asia/Dhaka",country: "Bangladesh",city: "Gazipur",region:"APAC"},
    { timezone: "Asia/Dhaka" ,country: "Bangladesh",city: "Khulna",region:"APAC"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Babruysk",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Baranavichy",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Barysaw",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Brest",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Homyel",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Hrodna",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Mahilyow",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Minsk",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Orsha",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Pinsk",region:"Europe"},
    { timezone: "Europe/Minsk",country: "Belarus",city: "Vitsyebsk",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Antwerpen",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Brugge",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "brussels",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Charleroi",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Ghent",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Hasselt",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Liege",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Mons",region:"Europe"},
    { timezone: "Europe/Brussels",country: "Belgium",city: "Namur",region:"Europe"},
    { timezone: "Atlantic/Bermuda",country: "Bermuda",city: "Hamilton",region:"America"},
    { timezone: "America/Sao_Paulo",country: "Brazil",city: "Brasilia",region:"America"},
    { timezone: "America/Sao_Paulo",country: "Brazil",city: "Porto Alegre",region:"America"},
    { timezone: "America/Sao_Paulo",country: "Brazil",city: "Rio de Janeiro",region:"America"},
    { timezone: "America/Sao_Paulo",country: "Brazil",city: "Sao Paulo",region:"America"},
    { timezone: "Europe/Sofia",country: "Bulgaria",city: "Burgas",region:"Europe"},
    { timezone: "Europe/Sofia",country: "Bulgaria",city: "Plovdiv",region:"Europe"},
    { timezone: "Europe/Sofia",country: "Bulgaria",city: "Sofia",region:"Europe"},
    { timezone: "Europe/Sofia" ,country: "Bulgaria",city: "Varna",region:"Europe"},
    { timezone: "Asia/Phnom_Penh",country: "Cambodia",city: "Phnom Penh",region:"APAC"},
    { timezone: "Africa/Douala" ,country: "Cameroon",city: "Bafoussam",region:"MEA"},
    { timezone: "America/Vancouver",country: "Canada",city: "Vancouver",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Ontario",region:"America"},
    { timezone: "America/Edmonton",country: "Canada",city: "Calgary",region:"America"},
    { timezone: "America/Edmonton",country: "Canada",city: "Edmonton",region:"America"},
    { timezone: "America/Regina",country: "Canada",city: "Regina",region:"America"},
    { timezone: "America/Winnipeg",country: "Canada",city: "Winnipeg",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Brampton",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Hamilton",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Kitchener",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "London",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "milton",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Mississauga",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Montreal",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "oshawa",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Ottawa",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Quebec",region:"America"},
    { timezone: "America/Toronto",country: "Canada",city: "Toronto",region:"America"},
    { timezone: "America/Halifax" ,country: "Canada",city: "Halifax",region:"America"},
    { timezone: "America/Santiago",country: "Chile",city: "Conception",region:"America"},
    { timezone: "America/Santiago",country: "Chile",city: "Santiago",region:"America"},
    { timezone: "America/Santiago",country: "Chile",city: "ValparaIso",region:"America"},
    { timezone: "Asia/Shanghai",country: "China",city: "Changchun",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Changsha",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Chengdu",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Fuzhou",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Guangzhou",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Guiyang",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Harbin",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Hefei",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Jinan",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Kunming",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Lanzhou",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Nanchang",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Shenyang",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Shenzhen",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Shijiazhuang",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Taiyuan",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Wuhan",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Xining",region:"APAC"},
    { timezone: "Asia/Shanghai",country: "China",city: "Zhengzhou",region:"APAC"},
    { timezone: "America/Bogota",country: "Colombia",city: "Barranquilla",region:"America"},
    { timezone: "America/Bogota",country: "Colombia",city: "Bogota",region:"America"},
    { timezone: "America/Bogota",country: "Colombia",city: "Cali",region:"America"},
    { timezone: "America/Bogota",country: "Colombia",city: "MedellIn",region:"America"},
    { timezone: "Europe/Zagreb",country: "Croatia",city: "Rijeka",region:"Europe"},
    { timezone: "Europe/Zagreb",country: "Croatia",city: "Split",region:"Europe"},
    { timezone: "Europe/Zagreb",country: "Croatia",city: "Zagreb",region:"Europe"},
    { timezone: "Asia/Nicosia",country: "Cyprus",city: "Lemosos",region:"Europe"},
    { timezone: "Asia/Nicosia",country: "Cyprus",city: "Nicosia",region:"Europe"},
    { timezone: "Europe/Prague",country: "Czech Republic",city: "Brno",region:"Europe"},
    { timezone: "Europe/Prague",country: "Czech Republic",city: "Ostrava",region:"Europe"},
    { timezone: "Europe/Prague" ,country: "Czech Republic",city: "Prague",region:"Europe"},
    { timezone: "Europe/Copenhagen",country: "Denmark",city: "Aalborg",region:"Europe"},
    { timezone: "Europe/Copenhagen",country: "Denmark",city: "Arhus",region:"Europe"},
    { timezone: "Europe/Copenhagen",country: "Denmark",city: "Kobenhavn",region:"Europe"},
    { timezone: "Europe/Copenhagen",country: "Denmark",city: "Odense",region:"Europe"},
    { timezone: "Africa/Cairo",country: "Egypt",city: "Alexandria",region:"Europe"},
    { timezone: "Africa/Cairo",country: "Egypt",city: "Cairo",region:"Europe"},
    { timezone: "Africa/Cairo",country: "Egypt",city: "Giza",region:"Europe"},
    { timezone: "Africa/Cairo",country: "Egypt",city: "Port Said",region:"Europe"},
    { timezone: "Europe/Tallinn",country: "Estonia",city: "Narva",region:"Europe"},
    { timezone: "Europe/Tallinn",country: "Estonia",city: "Tallinn",region:"Europe"},
    { timezone: "Europe/Tallinn" ,country: "Estonia",city: "Tartu",region:"Europe"},
    { timezone: "Africa/Addis_Ababa",country: "Ethiopia",city: "Addis-Ababa",region:"MEA"},
    { timezone: "Africa/Addis_Ababa",country: "Ethiopia",city: "Bahir Dar",region:"MEA"},
    { timezone: "Africa/Addis_Ababa",country: "Ethiopia",city: "Dire Dawa",region:"MEA"},
    { timezone: "Africa/Addis_Ababa",country: "Ethiopia",city: "Nazret",region:"MEA"},
    { timezone: "Europe/Helsinki",country: "Finland",city: "Helsinki",region:"Europe"},
    { timezone: "Europe/Helsinki",country: "Finland",city: "Tampere",region:"Europe"},
    { timezone: "Europe/Helsinki",country: "Finland",city: "Turku",region:"Europe"},
    { timezone: "Europe/Paris",country: "France",city: "Lille",region:"Europe"},
    { timezone: "Europe/Paris",country: "France",city: "Lyon",region:"Europe"},
    { timezone: "Europe/Paris",country: "France",city: "Marseille",region:"Europe"},
    { timezone: "Europe/Paris",country: "France",city: "Paris",region:"Europe"},
    { timezone: "Asia/Tbilisi",country: "Georgia",city: "Kutaisi",region:"Europe"},
    { timezone: "Asia/Tbilisi",country: "Georgia",city: "Rustavi",region:"Europe"},
    { timezone: "Asia/Tbilisi",country: "Georgia",city: "Tbilisi",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Berlin",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Cologne",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Dortmund",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Dusseldorf",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Essen",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "frankfurt",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Hamburg",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Munich",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "Stuttgart",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "darmstadt",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "heidelberg",region:"Europe"},
    { timezone: "Europe/Berlin",country: "Germany",city: "ulm",region:"Europe"},
    { timezone: "Africa/Accra",country: "Ghana",city: "Accra",region:"Europe"},
    { timezone: "Africa/Accra",country: "Ghana",city: "Kumasi",region:"Europe"},
    { timezone: "Africa/Accra",country: "Ghana",city: "Tamale",region:"Europe"},
    { timezone: "Europe/Athens",country: "Greece",city: "Athens",region:"Europe"},
    { timezone: "Europe/Athens",country: "Greece",city: "Patra",region:"Europe"},
    { timezone: "Europe/Athens",country: "Greece",city: "Piraeus",region:"Europe"},
    { timezone: "Europe/Athens",country: "Greece",city: "Thessaloniki",region:"Europe"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Aberdeen",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Fanling",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "hong kong",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Hung Hom",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Kwai Chung",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Kwun Tong",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Sai Wan Ho",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Shatin Station",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Tai Po",region:"APAC"},
    { timezone: "Asia/Hong_Kong",country: "Hong Kong",city: "Victoria City",region:"APAC"},
    { timezone: "Europe/Budapest",country: "Hungary",city: "Budapest",region:"Europe"},
    { timezone: "Europe/Budapest",country: "Hungary",city: "Debrecen",region:"Europe"},
    { timezone: "Europe/Budapest",country: "Hungary",city: "Miskolc",region:"Europe"},
    { timezone: "Atlantic/Reykjavik",country: "Iceland",city: "Reykjavik",region:"Europe"},
    { timezone: "Asia/Kolkata",country: "India",city: "Ahmedabad",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Bengaluru",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Bhopal",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Chandigarh",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Chennai",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Cochin",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Coimbatore",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Delhi",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Gurgaon",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Hyderabad",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Kolkata",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Mumbai",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Mysore",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Noida",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Pune",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Surat",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Thiruvananthapuram",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Vadodara",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Vijayawada",region:"India"},
    { timezone: "Asia/Kolkata",country: "India",city: "Visakhapatnam",region:"India"},
    { timezone: "Asia/Jakarta",country: "Indonesia",city: "Bandung",region:"APAC"},
    { timezone: "Asia/Jakarta",country: "Indonesia",city: "Jakarta",region:"APAC"},
    { timezone: "Asia/Jakarta",country: "Indonesia",city: "Surabaya",region:"APAC"},
    { timezone: "Asia/Tehran",country: "Iran",city: "Karaj",region:"MEA"},
    { timezone: "Asia/Tehran",country: "Iran",city: "Mashhad",region:"MEA"},
    { timezone: "Asia/Tehran",country: "Iran",city: "Tehran",region:"MEA"},
    { timezone: "Europe/Dublin",country: "Ireland",city: "Cork",region:"Europe"},
    { timezone: "Europe/Dublin",country: "Ireland",city: "Dublin",region:"Europe"},
    { timezone: "Asia/Jerusalem",country: "Israel",city: "Haifa",region:"MEA"},
    { timezone: "Asia/Jerusalem",country: "Israel",city: "Jerusalem",region:"MEA"},
    { timezone: "Asia/Jerusalem",country: "Israel",city: "Tel Aviv",region:"MEA"},
    { timezone: "Europe/Rome",country: "Italy",city: "Milan",region:"Europe"},
    { timezone: "Europe/Rome",country: "Italy",city: "Rome",region:"Europe"},
    { timezone: "America/Jamaica",country: "Jamaica",city: "Kingston",region:"America"},
    { timezone: "America/Jamaica",country: "Jamaica",city: "Spanish Town",region:"America"},
    { timezone: "Asia/Tokyo",country: "Japan",city: "Osaka",region:"APAC"},
    { timezone: "Asia/Tokyo",country: "Japan",city: "Tokyo",region:"APAC"},
    { timezone: "Asia/Tokyo" ,country: "Japan",city: "Yokohama",region:"APAC"},
    { timezone: "Asia/Amman",country: "Jordan",city: "Amman",region:"Europe"},
    { timezone: "Asia/Amman",country: "Jordan",city: "Az Zarqa",region:"Europe"},
    { timezone: "Asia/Kuwait",country: "Kuwait",city: "Al Ahmadi",region:"MEA"},
    { timezone: "Asia/Kuwait",country: "Kuwait",city: "Al Jahra",region:"MEA"},
    { timezone: "Asia/Kuwait",country: "Kuwait",city: "Kuwait",region:"MEA"},
    { timezone: "Europe/Riga",country: "Latvia",city: "Daugavpils",region:"Europe"},
    { timezone: "Europe/Riga",country: "Latvia",city: "Liepaga",region:"Europe"},
    { timezone: "Europe/Riga" ,country: "Latvia",city: "Riga",region:"Europe"},
    { timezone: "Asia/Beirut",country: "Lebanon",city: "Beirut",region:"Europe"},
    { timezone: "Asia/Beirut",country: "Lebanon",city: "Trablous",region:"Europe"},
    { timezone: "Europe/Vilnius",country: "Lithuania",city: "Kaunas",region:"Europe"},
    { timezone: "Europe/Vilnius",country: "Lithuania",city: "Vilnius",region:"Europe"},
    { timezone: "Europe/Luxembourg",country: "Luxembourg",city: "Luxembourg",region:"Europe"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Alor Setar",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "George Town",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Ipoh",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Kangar",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Kota Bharu",region:"APAC"},
    { timezone: "Asia/Kuching",country: "Malaysia",city: "Kota Kinabalu",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "kuala lumpur",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Kuala Terengganu",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Kuantan",region:"APAC"},
    { timezone: "Asia/Kuching",country: "Malaysia",city: "Kuching",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Malacca City",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "penang",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "Seremban",region:"APAC"},
    { timezone: "Asia/Kuala_Lumpur",country: "Malaysia",city: "shah alam",region:"APAC"},
    { timezone: "Asia/Kuching",country: "Malaysia",city: "Victoria",region:"APAC"},
    { timezone: "Indian/Maldives" ,country: "Maldives",city: "Male",region:"APAC"},
    { timezone: "Europe/Malta",country: "Malta",city: "Lagos",region:"Europe"},
    { timezone: "Europe/Malta",country: "Malta",city: "Valletta",region:"Europe"},
    { timezone: "America/Ojinaga",country: "Mexico",city: "Ciudad Juarez",region:"America"},
    { timezone: "America/Mexico_City",country: "Mexico",city: "Ecatepec",region:"America"},
    { timezone: "America/Mexico_City",country: "Mexico",city: "Guadalajara",region:"America"},
    { timezone: "America/Mexico_City",country: "Mexico",city: "Leon",region:"America"},
    { timezone: "America/Mexico_City",country: "Mexico",city: "Mexico City",region:"America"},
    { timezone: "America/Monterrey",country: "Mexico",city: "Monterrey",region:"America"},
    { timezone: "America/Mexico_City",country: "Mexico",city: "Puebla",region:"America"},
    { timezone: "America/Tijuana",country: "Mexico",city: "Tijuana",region:"America"},
    { timezone: "America/Mexico_City",country: "Mexico",city: "Zapopan",region:"America"},
    { timezone: "Asia/Ulaanbaatar",country: "Mongolia",city: "Darhan",region:"APAC"},
    { timezone: "Asia/Ulaanbaatar",country: "Mongolia",city: "Erdenet",region:"APAC"},
    { timezone: "Asia/Ulaanbaatar" ,country: "Mongolia",city: "Ulan Bator",region:"APAC"},
    { timezone: "Europe/Podgorica",country: "Montenegro",city: "Podgorica",region:"Europe"},
    { timezone: "Asia/Yangon",country: "Myanmar",city: "Bago",region:"APAC"},
    { timezone: "Asia/Yangon",country: "Myanmar",city: "Mandalay",region:"APAC"},
    { timezone: "Asia/Yangon",country: "Myanmar",city: "Mawlamyine",region:"APAC"},
    { timezone: "Asia/Yangon",country: "Myanmar",city: "Yangon",region:"APAC"},
    { timezone: "Asia/Kathmandu",country: "Nepal",city: "Kathmandu",region:"APAC"},
    { timezone: "Europe/Amsterdam",country: "Netherlands",city: "Amsterdam",region:"Europe"},
    { timezone: "Europe/Amsterdam",country: "Netherlands",city: "Rotterdam",region:"Europe"},
    { timezone: "Europe/Amsterdam",country: "Netherlands",city: "The Hague",region:"Europe"},
    { timezone: "Europe/Amsterdam",country: "Netherlands",city: "eindhoven",region:"Europe"},
    { timezone: "Pacific/Auckland",country: "New Zealand",city: "Auckland",region:"Oceania"},
    { timezone: "Pacific/Auckland",country: "New Zealand",city: "Christchurch",region:"Oceania"},
    { timezone: "Pacific/Auckland",country: "New Zealand",city: "Palmerston North",region:"Oceania"},
    { timezone: "Pacific/Auckland",country: "New Zealand",city: "Wellington",region:"Oceania"},
    { timezone: "Pacific/Auckland" ,country: "New Zealand",city: "Whanganui",region:"Oceania"},
    { timezone: "Africa/Lagos",country: "Nigeria",city: "abuja",region:"MEA"},
    { timezone: "Africa/Lagos",country: "Nigeria",city: "Lagos",region:"MEA"},
    { timezone: "Africa/Lagos",country: "Nigeria",city: "Ibadan",region:"MEA"},
    { timezone: "Africa/Lagos",country: "Nigeria",city: "Kano",region:"MEA"},
    { timezone: "Africa/Lagos",country: "Nigeria",city: "Port Harcourt",region:"MEA"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Changwon",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Goyang",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Gwangju",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Gyeongsang",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Nampo",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Pyongyang",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Songnam",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Suwon",region:"Apac"},
    { timezone: "Asia/Pyongyang",country: "North Korea",city: "Ulsan",region:"Apac"},
    { timezone: "Europe/London",country: "Northern Ireland",city: "Belfast",region:"Europe"},
    { timezone: "Europe/London",country: "Northern Ireland",city: "Derry",region:"Europe"},
    { timezone: "Europe/Oslo",country: "Norway",city: "Bergen",region:"Europe"},
    { timezone: "Europe/Oslo",country: "Norway",city: "Oslo",region:"Europe"},
    { timezone: "Asia/Muscat",country: "Oman",city: "As Sib",region:"MEA"},
    { timezone: "Asia/Muscat",country: "Oman",city: "Muscat",region:"MEA"},
    { timezone: "Asia/Muscat" ,country: "Oman",city: "Salalah",region:"MEA"},
    { timezone: "Asia/Karachi",country: "Pakistan",city: "Karachi",region:"APAC"},
    { timezone: "Asia/Karachi",country: "Pakistan",city: "Quetta",region:"APAC"},
    { timezone: "America/Panama",country: "Panama",city: "Colon",region:"America"},
    { timezone: "America/Panama",country: "Panama",city: "Panama City",region:"America"},
    { timezone: "Pacific/Port_Moresby",country: "Papua New Guinea",city: "Port Moresby",region:"Oceania"},
    { timezone: "America/Asuncion",country: "Paraguay",city: "Asuncion",region:"Europe"},
    { timezone: "America/Asuncion",country: "Paraguay",city: "San Lorenzo",region:"Europe"},
    { timezone: "America/Lima",country: "Peru",city: "Arequipa",region:"America"},
    { timezone: "America/Lima",country: "Peru",city: "Callao",region:"America"},
    { timezone: "America/Lima" ,country: "Peru",city: "Lima",region:"America"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Angeles",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Antipolo",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Bacolod",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Baguio",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Batangas city",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Birian",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Bttuan",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Cabadbaran",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Cabanatuan",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Cabuyao",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Calamba",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Cebu city",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "makati",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "manila",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Palayan",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Tacloban",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Tarlac city",region:"APAC"},
    { timezone: "Asia/Manila",country: "Philippines",city: "Zamboanga City",region:"APAC"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Belgrade",region:"Europe"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Katowice",region:"Europe"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Krakow",region:"Europe"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Lodz",region:"Europe"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Nis",region:"Europe"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Novi Sad",region:"Europe"},
    { timezone: "Europe/Warsaw",country: "Poland",city: "Warsaw",region:"Europe"},
    { timezone: "Europe/Warsaw" ,country: "Poland",city: "wroclaw",region:"Europe"},
    { timezone: "Europe/Lisbon",country: "Portugal",city: "Braga",region:"Europe"},
    { timezone: "Europe/Lisbon",country: "Portugal",city: "Lisbon",region:"Europe"},
    { timezone: "Europe/Lisbon",country: "Portugal",city: "Porto",region:"Europe"},
    { timezone: "Asia/Qatar",country: "Qatar",city: "Al rayyan",region:"MEA"},
    { timezone: "Asia/Qatar",country: "Qatar",city: "Doha",region:"MEA"},
    { timezone: "Indian/Reunion",country: "Reunion",city: "St Denis",region:"Europe"},
    { timezone: "Europe/Bucharest",country: "Romania",city: "Bucharest",region:"Europe"},
    { timezone: "Europe/Bucharest",country: "Romania",city: "cluj napoca",region:"Europe"},
    { timezone: "Europe/Bucharest",country: "Romania",city: "Iasi",region:"Europe"},
    { timezone: "Europe/Moscow",country: "Russia",city: "Moscow",region:"Europe"},
    { timezone: "Asia/Novosibirsk",country: "Russia",city: "Novosibirsk",region:"Europe"},
    { timezone: "Europe/Moscow",country: "Russia",city: "Saint Petersburg",region:"Europe"},
    { timezone: "Europe/San_Marino",country: "San Marino",city: "San Marino",region:"Europe"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "Ad Damman",region:"MEA"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "al khobar",region:"MEA"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "Jeddah",region:"MEA"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "Makkah",region:"MEA"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "Medina",region:"MEA"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "Riyadh",region:"MEA"},
    { timezone: "Asia/Riyadh",country: "Saudi Arabia",city: "dammam",region:"MEA"},
    { timezone: "Europe/Belgrade",country: "Serbia",city: "Belgrade",region:"Europe"},
    { timezone: "Europe/Belgrade",country: "Serbia",city: "Novi Sad",region:"Europe"},
    { timezone: "Asia/Singapore",country: "Singapore",city: "Singapore",region:"APAC"},
    { timezone: "Europe/Bratislava",country: "Slovakia",city: "Bratislava",region:"Europe"},
    { timezone: "Europe/Bratislava",country: "Slovakia",city: "Kosice",region:"Europe"},
    { timezone: "Europe/Ljubljana",country: "Slovenia",city: "Ljubljana",region:"Europe"},
    { timezone: "Europe/Ljubljana" ,country: "Slovenia",city: "Maribor",region:"Europe"},
    { timezone: "Africa/Johannesburg",country: "South Africa",city: "Benoni",region:"MEA"},
    { timezone: "Africa/Johannesburg",country: "South Africa",city: "Cape Town",region:"MEA"},
    { timezone: "Africa/Johannesburg",country: "South Africa",city: "Durban",region:"MEA"},
    { timezone: "Africa/Johannesburg",country: "South Africa",city: "Johannesburg",region:"MEA"},
    { timezone: "Africa/Johannesburg",country: "South Africa",city: "pretoria",region:"MEA"},
    { timezone: "Asia/Seoul",country: "South Korea",city: "Busan",region:"APAC"},
    { timezone: "Asia/Seoul",country: "South Korea",city: "Daegu",region:"APAC"},
    { timezone: "Asia/Seoul",country: "South Korea",city: "Daejeon",region:"APAC"},
    { timezone: "Asia/Seoul",country: "South Korea",city: "Incheon",region:"APAC"},
    { timezone: "Asia/Seoul",country: "South Korea",city: "Seoul",region:"APAC"},
    { timezone: "Africa/Juba",country: "South Sudan",city: "Malakal",region:"MEA"},
    { timezone: "Africa/Juba",country: "South Sudan",city: "Yei",region:"MEA"},
    { timezone: "Europe/Madrid",country: "Spain",city: "Barcelona",region:"Europe"},
    { timezone: "Europe/Madrid",country: "Spain",city: "Bilbao",region:"Europe"},
    { timezone: "Europe/Madrid",country: "Spain",city: "Madrid",region:"Europe"},
    { timezone: "Europe/Madrid",country: "Spain",city: "Seville",region:"Europe"},
    { timezone: "Europe/Madrid" ,country: "Spain",city: "Valencia",region:"Europe"},
    { timezone: "Asia/Colombo",country: "Sri Lanka",city: "Colombo",region:"APAC"},
    { timezone: "Asia/Colombo",country: "Sri Lanka",city: "Jaffna",region:"APAC"},
    { timezone: "Asia/Colombo",country: "Sri Lanka",city: "Moratuwa",region:"APAC"},
    { timezone: "Europe/Stockholm",country: "Sweden",city: "Gothenburg",region:"Europe"},
    { timezone: "Europe/Stockholm",country: "Sweden",city: "Huddinge",region:"Europe"},
    { timezone: "Europe/Stockholm",country: "Sweden",city: "Nacka",region:"Europe"},
    { timezone: "Europe/Stockholm",country: "Sweden",city: "Stockholm",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Basel Land",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Bern",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Geneva",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Lausanne",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Lucerne",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Lugano",region:"Europe"},
    { timezone: "Europe/Zurich",country: "Switzerland",city: "Saint Gallen",region:"Europe"},
    { timezone: "Europe/Zurich" ,country: "Switzerland",city: "Zurich",region:"Europe"},
    { timezone: "Asia/Taipei",country: "Taiwan",city: "Kaohsiung city",region:"APAC"},
    { timezone: "Asia/Taipei",country: "Taiwan",city: "New Taipei City",region:"APAC"},
    { timezone: "Asia/Taipei",country: "Taiwan",city: "Taichung city",region:"APAC"},
    { timezone: "Asia/Taipei",country: "Taiwan",city: "Tainan city",region:"APAC"},
    { timezone: "Asia/Taipei",country: "Taiwan",city: "Taipei city",region:"APAC"},
    { timezone: "Asia/Taipei",country: "Taiwan",city: "Taoyuan city",region:"APAC"},
    { timezone: "Asia/Bangkok",country: "Thailand",city: "Bangkok",region:"APAC"},
    { timezone: "Africa/Tunis",country: "Tunisia",city: "Tunis",region:"Europe"},
    { timezone: "Europe/Istanbul",country: "Turkey",city: "Adana",region:"MEA"},
    { timezone: "Europe/Istanbul",country: "Turkey",city: "Ankara",region:"MEA"},
    { timezone: "Europe/Istanbul",country: "Turkey",city: "Bursa",region:"MEA"},
    { timezone: "Europe/Istanbul",country: "Turkey",city: "Istanbul",region:"MEA"},
    { timezone: "Europe/Istanbul",country: "Turkey",city: "Izmir",region:"MEA"},
    { timezone: "Europe/Istanbul",country: "Turkey",city: "Kirklareli",region:"MEA"},
    { timezone: "Asia/Dubai",country: "UAE",city: "Abu Dhabi",region:"MEA"},
    { timezone: "Asia/Dubai",country: "UAE",city: "Dubai",region:"MEA"},
    { timezone: "Asia/Dubai",country: "UAE",city: "Sharjah",region:"MEA"},
    { timezone: "Europe/Kyiv",country: "Ukraine",city: "Kharkiv",region:"Europe"},
    { timezone: "Europe/Kyiv" ,country: "Ukraine",city: "Kiev",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Birmingham",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Bristol",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Edinburgh",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Glasgow",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Leeds",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Leicester",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Liverpool",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "London",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Manchester",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "Sheffield",region:"Europe"},
    { timezone: "Europe/London",country: "United Kingdom",city: "cambridge",region:"Europe"},
    { timezone: "America/Anchorage",country: "USA",city: "Anchorage",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Anaheim",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Bakersfield",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Fresno",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Henderson",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Irvine",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "La Jolla",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Las Vegas",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Long Beach",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Los Angeles",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Milpitas",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Oakland",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Orange",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Orange County",region:"America"},
    { timezone: "America/Phoenix",country: "USA",city: "Phoenix",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Pleasanton",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Portland",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Riverside",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Sacramento",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "San Diego",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "San Francisco",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "San Jose",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "San Mateo",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Santa Ana",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Seattle",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Spokane",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Sunnyvale",region:"America"},
    { timezone: "America/Phoenix",country: "USA",city: "Tucson",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Walnut Creek",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "Bellevue",region:"America"},
    { timezone: "America/Los_Angeles",country: "USA",city: "redmond",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Albuquerque",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Boise",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Cheyenne",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Colorado Springs",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Denver",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Rapid City",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "Salt Lake City",region:"America"},
    { timezone: "America/Denver",country: "USA",city: "aurora",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Arlington",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Austin",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Baton Rouge",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Cedar Rapids",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Chicago",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Dallas",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Des Moines",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Fargo",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Fort Worth",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Houston",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Huntsville",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Jackson",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Jefferson City",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Kansas City",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Little Rock",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Madison",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Memphis",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Milwaukee",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Minneapolis",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Montgomery",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Nashville",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "New Orleans",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Oklahoma City",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Omaha",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Overland Park",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Rockford",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "San Antonio",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Sioux Falls",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Springfield",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "St Louis",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Tulsa",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "West Des Moines",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Wichita",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "frisco",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "Irving",region:"America"},
    { timezone: "America/Chicago",country: "USA",city: "saint paul",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "ashburn",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Athens",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Atlanta",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Baltimore",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Boston",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Brooklyn",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Buffalo",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Burlington",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Carmel",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Chapel Hill",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Charleston",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Charlotte",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Cincinnati",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Cleveland",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Columbia",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Columbus",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Cumming",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Detroit",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Edison",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Fort Lauderdale",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Greenville",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Hartford",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Herndon",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Indianapolis",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Jacksonville",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Jersey City",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Louisville",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Manchester",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "McLean",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Miami",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "mount laurel",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "New Jersey",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "New York",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Newark",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Norfolk",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Orlando",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Philadelphia",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Pittsburgh",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Providence",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Raleigh",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Richmond",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Rochester",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Sewickley",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Tampa",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Trenton",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Washington",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Wilmington",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Fairfax",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Greensboro",region:"America"},
    { timezone: "America/New_York",country: "USA",city: "Mechanicsville",region:"America"},
    { timezone: "Asia/Ho_Chi_Minh",country: "Vietnam",city: "Ha Noi",region:"APAC"},
    { timezone: "Asia/Ho_Chi_Minh",country: "Vietnam",city: "Ho Chi Minh City",region:"APAC"},
    
    ];
    export default countryData;